address:
  limit_page: 10
order:
  limit_page: 10
address:
  limit_page: 10
shipping:
  limit_page: 5
  title:
    maximum: 255
  price:
    numericality: 0
products:
  record_per_page: 8
  limit_page: 5
URL_IMAGE: "/upload/"
users:
  limit_page: 5
brands:
  limit_page: 5
categories:
  limit_page: 5
slides:
  limit_page: 5
user:
  email:
    max_length: 255
  name:
    max_length: 50
  password:
    min_length: 6
limit_picture_size: 5
